-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."composer "
(
    composer_id serial NOT NULL,
    composer_name character varying NOT NULL,
    birthday date NOT NULL,
    deathday date,
    home_page character varying,
    PRIMARY KEY (composer_id)
);

CREATE TABLE IF NOT EXISTS public.piece
(
    piece_id serial NOT NULL,
    collection_id integer,
    piece_name character varying NOT NULL,
    published_date date,
    PRIMARY KEY (piece_id)
);

CREATE TABLE IF NOT EXISTS public.collection
(
    collection_id serial NOT NULL,
    collection_name character varying NOT NULL,
    PRIMARY KEY (collection_id)
);

CREATE TABLE IF NOT EXISTS public.genre
(
    genre_id serial NOT NULL,
    genre_name character varying NOT NULL,
    PRIMARY KEY (genre_id)
);

CREATE TABLE IF NOT EXISTS public.composer_piece
(
    composer_id integer NOT NULL,
    piece_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.genre_piece
(
    genre_id integer NOT NULL,
    piece_id integer NOT NULL
);

ALTER TABLE IF EXISTS public.piece
    ADD CONSTRAINT "collection_id FK" FOREIGN KEY (collection_id)
    REFERENCES public.collection (collection_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.composer_piece
    ADD CONSTRAINT "piece_id FK" FOREIGN KEY (piece_id)
    REFERENCES public.piece (piece_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.composer_piece
    ADD CONSTRAINT "composer_id FK" FOREIGN KEY (composer_id)
    REFERENCES public."composer " (composer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.genre_piece
    ADD CONSTRAINT genre_id FOREIGN KEY (genre_id)
    REFERENCES public.genre (genre_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.genre_piece
    ADD CONSTRAINT piece_id FOREIGN KEY (piece_id)
    REFERENCES public.piece (piece_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;